---
title: "R Notebook"
output: html_notebook
---

ANALYSE SPATIALE DES DONNEES 

TRAITEMENT DES DONNEES 
#----
```{r}
load("don.RData")
ls()
summary(don)
head(don)
str(don)
colnames(don)
```

```{r}
require(leaflet.minicharts)
library(sp)
library(magrittr)
?read.xlsx
cd <- read_excel("Centre_departement.xlsx", skip = 1)
head(cd)
print(cd$`ɸ (° ' "")`)
colnames(cd)
cd$`ɸ (° ' "")` <- gsub(" ", "", cd$`ɸ (° ' "")`)
cd$`ɸ (° ' "")` <- char2dms(cd$`ɸ (° ' "")`, chd='°', chm="'", chs='"') %>% as.numeric()
cd$`Ʌ (° ' "")` <- char2dms(cd$`Ʌ (° ' "")`, chd='°', chm="'", chs='"') %>% as.numeric()

names(cd)[1] <- "dep"
names(cd)[5] <- "lat"
names(cd)[4] <- "long"

# Faire une jointure gauche pour garder tous les départements de l'ancien dataframe
merged_df <- merge(don, cd[, c("dep", "lat", "long")], by = "dep", all.x = TRUE, suffixes = c("_ancien", "_nouveau"))
# Remplacer les valeurs de latitude et longitude
summary(don)
summary(merged_df)
condition <- merged_df$lat_ancien == 0 | is.na(merged_df$lat_ancien)
sum(condition)  # Compte le nombre de TRUE
merged_df$lat_nouveau[condition]  # Affiche les valeurs correspondantes
length(merged_df$lat_nouveau[condition])  # Longueur des valeurs à assigner
merged_df$lat_ancien[condition] <- merged_df$lat_nouveau[condition]

condition2 <- merged_df$long_ancien == 0 | is.na(merged_df$long_ancien)
merged_df$long_ancien[condition2] <- merged_df$long_nouveau[condition2]

# Afficher les résultats après remplacement
head(merged_df)
summary(merged_df)
colnames(merged_df) 
data <- merged_df %>% select(-lat_nouveau, -long_nouveau)
summary(data)
```



ELABORATION DE CARTES 



ELABORATION DE CARTES 


#---- 
```{r}
#install.packages("leaflet.minicharts")
library(leaflet.minicharts)
library(leaflet)
#BASEMAP
tilesURL <- "http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
basemap <- leaflet(width = "100%", height = "400px") %>%
  addTiles(tilesURL)
?group_by
# Supprimer les zéros en tête des départements
data$dep <- sub("^0+", "", data$dep)
colnames(data)
data$sexe
result_ds <- data %>%
  group_by(dep) %>%
  summarise(
    lat = mean(lat_ancien, na.rm = TRUE),  # Moyenne de la latitude
    long = mean(long_ancien, na.rm = TRUE),  # Moyenne de la longitude
    nombre_lignes = n(),  # Nombre de lignes par département
    femmes = sum(sexe == "Feminin", na.rm = TRUE),  # Nombre de femmes
    hommes = sum(sexe == "Masculin", na.rm = TRUE)   # Nombre d'hommes
  ) %>%
  mutate(
    pourcentage_femmes = (femmes / nombre_lignes) * 100,  # Pourcentage de femmes
    pourcentage_hommes = (hommes / nombre_lignes) * 100    # Pourcentage d'hommes
  ) %>%
  select(dep, nombre_lignes, pourcentage_femmes, pourcentage_hommes, lat, long)


print(result_ds)
summary(result_ds)
```
```{r}
colors <- c("blue","pink")
# Assurez-vous que le vecteur de popups a la bonne longueur
if(length(popup_messages) != nrow(result_ds)) {
  stop("La longueur des popups ne correspond pas au nombre de départements.")
}
basemap %>% 
  addMinicharts(
    result_ds$long, result_ds$lat, 
    chartdata = result_ds[, c("pourcentage_hommes", "pourcentage_femmes")],
    type = "pie",
    #time = prodRegions$month,
    colorPalette = colors,
    width = 15, height = 15,
    showLabels = TRUE,
    #popup = popup
  )


```

Carte par sexe par departement par annee
```{r}
# Étape 1 : Calcul des latitudes et longitudes moyennes par département
lat_long <- data %>%
  group_by(dep) %>%
  summarise(
    lat = mean(lat_ancien, na.rm = TRUE),  # Moyenne de la latitude
    long = mean(long_ancien, na.rm = TRUE)   # Moyenne de la longitude
  )

# Étape 2 : Calcul des statistiques par département et année
stats_sexe <- data %>%
  group_by(dep, an) %>%  # Regroupement par département et année
  summarise(
    nombre_lignes = n(),  # Nombre de lignes par département
    femmes = sum(sexe == "Feminin", na.rm = TRUE),  # Nombre de femmes
    hommes = sum(sexe == "Masculin", na.rm = TRUE)   # Nombre d'hommes
  ) %>%
  mutate(
    pourcentage_femmes = (femmes / nombre_lignes) * 100,  # Pourcentage de femmes
    pourcentage_hommes = (hommes / nombre_lignes) * 100    # Pourcentage d'hommes
  )

# Étape 3 : Fusion des résultats
result_ds <- stats_sexe %>%
  left_join(lat_long, by = "dep")  # Ajoutez les latitudes et longitudes

# Créez les mini-charts
basemap %>% 
  addMinicharts(
    result_ds$long,
    result_ds$lat, 
    chartdata = result_ds[, c("pourcentage_hommes", "pourcentage_femmes")],
    type = "pie",
    colorPalette = colors,
    width = 15, 
    height = 15,
    showLabels = TRUE,
    time = result_ds$an  # Utilisez la colonne d'année ici
  )



```

GRAVITE 
```{r}
lat_long <- data %>%
  group_by(dep) %>%
  summarise(
    lat = mean(lat_ancien, na.rm = TRUE),  # Moyenne de la latitude
    long = mean(long_ancien, na.rm = TRUE)   # Moyenne de la longitude
  )


result_ds <- data %>%
  group_by(dep, an, grav) %>%
  summarise(count = n(), .groups = 'drop') %>%
  spread(key = grav, value = count, fill = 0) # Spread severity levels into columns


result_ds <- result_ds %>%
  left_join(lat_long, by = "dep")

unique(result_ds$grav)

severity_colors <- c("green", 
                     "yellow", 
                     "orange", 
                     "red")
colnames(result_ds)
?addMinicharts
basemap %>%
  addMinicharts(
    lng = result_ds$long, 
    lat = result_ds$lat, 
    chartdata = as.data.frame(result_ds[, c("Indemne", "Blessé léger", "Blessé hospitalisé", "Tué")]),
    type = "bar",
    time = result_ds$an,  # Définir l'année ici
    colorPalette = severity_colors, # Utiliser la palette de couleurs définie
    width = 70, height = 70,
    #showLabels = TRUE
  )

```
